language: python
python:
    "3.6.3"
install:
     "pip install -r requirements.txt"
script:
     - nosetests
     - nosetests --with-coverage --source="yummy_recipes/tests/"
     - coveralls
after_success:
     - "coveralls"

