language: python
python:
    "3.6.3"
install:
     "pip install -r requirements.txt"
script:
     - "python test_users.py"
     - "python test_recipes.py"
     - "coverage run test_users.py"
     - "coverage run test_recipes.py"
     - "coverage run app/__init.py"
     - "coverage run app/__init.py"
     - "coverage run recipes.py"
     - "coverage run users.py"
after_success: coveralls

